apiVersion: v1
data:
  metricbeat.yml: |
    metricbeat.modules:
    - module: mysql
      #enabled: true
      metricsets:
        - status
        - galera_status
        - performance
        #- query
      period: 10s

      # Host DSN should be defined as "user:pass@tcp(127.0.0.1:3306)/"
      # or "unix(/var/lib/mysql/mysql.sock)/",
      # or another DSN format supported by <https://github.com/Go-SQL-Driver/MySQL/>.
      # The username and password can either be set in the DSN or using the username
      # and password config options. Those specified in the DSN take precedence.
      hosts: ["root:${MYSQL_ROOT_PASSWORD:qwerty}@tcp(127.0.0.1:3306)/"]

      # Username of hosts. Empty by default.
      #username: root

      # Password of hosts. Empty by default.
      #password: secret

      # By setting raw to true, all raw fields from the status metricset will be added to the event.
      #raw: false
    output:
      elasticsearch:
        host: '${NODE_NAME}'
        hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
        username: ${ELASTICSEARCH_USERNAME}
        password: ${ELASTICSEARCH_PASSWORD}
        ssl.certificate_authorities:
          - /etc/certificate/ca.crt
kind: ConfigMap
metadata:
  labels:
    app: mysql      
  name: metricbeat-config
