apiVersion: v1
data:
  my.cnf: |
    [mysqld_safe]
    log_error=/var/log/mysql/error.log

    [mysqld]
    pid-file= /var/run/mysqld/mysqld.pid
    socket= /var/run/mysqld/mysqld.sock
    datadir= /var/lib/mysql
    secure-file-priv= NULL
    log_error= /var/log/mysql/error.log
    general_log_file= /var/log/mysql/mysql.log
    general_log=1
    slow_query_log = 1
    long_query_time = 3
    slow_query_log_file = /var/log/mysql/slow-query.log
    # Custom config should go here
    # !includedir /etc/mysql/conf.d/
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: default
  labels:
    app: mysql
