apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        fsGroup: 1000
        #runAsUser: 1      
      volumes:
        - name: mysql-persistent-storage
          emptyDir: {}
          #hostPath:
          #  path: /mnt/data/mysql
          #  type: DirectoryOrCreate
        - name: config-volume
          configMap:
            name: mysql-config
            optional: true
        - name: kcerts
          secret:
            secretName: quickstart-kb-http-certs-public
        - name: certs
          secret:
            secretName: quickstart-es-http-certs-public
        - name: filebeat-config
          configMap:
            name: filebeat-config
            items:
              - key: filebeat.yml
                path: filebeat.yml    
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.5.0
          args: ["-c", "/usr/share/filebeat/filebeat.yml","-e"]
          env:
          - name: ELASTICSEARCH_HOST
            value: https://quickstart-es-http
          - name: ELASTICSEARCH_PORT
            value: "9200"
          - name: ELASTICSEARCH_USERNAME
            value: elastic
          - name: ELASTICSEARCH_PASSWORD
            value: 1H43EJIdAciKth08Y4eK5524
          - name: ELASTIC_CLOUD_ID
            value:
          - name: ELASTIC_CLOUD_AUTH
            value:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          volumeMounts:
          - name: certs
            mountPath: /etc/certificate/ca.crt
            readOnly: true
            subPath: ca.crt
          - name: kcerts
            mountPath: /etc/certificate/kibana/ca.crt
            readOnly: true
            subPath: ca.crt
          - name: mysql-persistent-storage
            mountPath: /var/log/mysql
          - name: filebeat-config
            mountPath: /usr/share/filebeat/filebeat.yml
            subPath: filebeat.yml        
        - image: percona
          name: mysql
          # command: ["/bin/sh", "-c", "chown -R 1000:0 /var/log/mysql"]
          env:
          # Use secret in real usage
          - name: MYSQL_ROOT_PASSWORD
            value: qwerty
          ports:
          - containerPort: 3306
          name: mysql
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/log/mysql
          - name: config-volume
            mountPath: /etc/my.cnf.d
